apiVersion: batch/v1
kind: Job
metadata:
  name: myjob-mysql
  labels:
    purpose: demonstrate-envars
spec:
  template:
    spec:
      initContainers:
        - name: init-myjob-mysql-container
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pass1
            - name: MYSQL_DATABASE
              value: app
            - name: MYSQL_USER
              value: devuser
            - name: MYSQL_PASSWORD
              value: devpass
          command: [ "/bin/sh", "-c" ]
          args:
            - echo starting;
              echo 'Execute query:' mysql -u root -p$MYSQL_ROOT_PASSWORD -e \'SHOW GRANTS FOR $(MYSQL_USER)\';
              mysql -u root -p$MYSQL_ROOT_PASSWORD -e \'SHOW databases\';
              echo done;
      containers:
        - name: myjob-mysql-container
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pass1
          command:
            - "echo 'HOLISSSS!!' && sleep 30"
      restartPolicy: Never
  backoffLimit: 1