apiVersion: v1
kind: Pod
metadata:
  name: mysql-test
  labels:
    purpose: demonstrate-envars
    app: mysql-server
spec:
  containers:
    - name: mysql-test-container
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass1
        - name: MYSQL_DATABASE
          value: app
        - name: MYSQL_USER
          value: devuser
        - name: MYSQL_PASSWORD
          value: devpass
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pv-claim